//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 12:07:42 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents a bore position and effective diameter,
 * 				measured from an arbitrary position, greater positions toward the
 * 				foot of the instrument. Diameters between borePoints are linearly
 * 				interpolated. This list includes borePoints above and below the
 * 				mouthpiece position.
 * 			
 * 
 * <p>Java class for BorePoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BorePoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="borePosition" type="{http://www.wwidesigner.com/Instrument}Dimension"/>
 *         &lt;element name="boreDiameter" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BorePoint", propOrder = {
    "borePosition",
    "boreDiameter"
})
public class BorePoint {

    protected double borePosition;
    protected double boreDiameter;

    /**
     * Gets the value of the borePosition property.
     * 
     */
    public double getBorePosition() {
        return borePosition;
    }

    /**
     * Sets the value of the borePosition property.
     * 
     */
    public void setBorePosition(double value) {
        this.borePosition = value;
    }

    /**
     * Gets the value of the boreDiameter property.
     * 
     */
    public double getBoreDiameter() {
        return boreDiameter;
    }

    /**
     * Sets the value of the boreDiameter property.
     * 
     */
    public void setBoreDiameter(double value) {
        this.boreDiameter = value;
    }

}
