//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.30 at 09:14:21 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents a bore position and effective diameter,
 * 				measured from an arbitrary position, greater positions toward the
 * 				foot of the instrument. Diameters between
 * 				borePoints are linearly
 * 				interpolated.
 * 			
 * 
 * <p>Java class for BorePoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BorePoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="borePosition" type="{http://www.wwidesigner.com/Instrument}Dimension"/>
 *         &lt;element name="boreDiameter" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BorePoint", propOrder = {
    "borePosition",
    "boreDiameter"
})
public class BorePoint {

    @XmlElement(required = true)
    protected Dimension borePosition;
    @XmlElement(required = true)
    protected ZeroOrMore boreDiameter;

    /**
     * Gets the value of the borePosition property.
     * 
     * @return
     *     possible object is
     *     {@link Dimension }
     *     
     */
    public Dimension getBorePosition() {
        return borePosition;
    }

    /**
     * Sets the value of the borePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimension }
     *     
     */
    public void setBorePosition(Dimension value) {
        this.borePosition = value;
    }

    /**
     * Gets the value of the boreDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getBoreDiameter() {
        return boreDiameter;
    }

    /**
     * Sets the value of the boreDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setBoreDiameter(ZeroOrMore value) {
        this.boreDiameter = value;
    }

}
