//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 12:07:42 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A tone hole with optional key mechanism. The tone
 * 				hole assumes a cylindrical shape with a radiused inner edge. More
 * 				complexity is possible, including truncated conical profiles and
 * 				angled holes.
 * 			
 * 
 * <p>Java class for Hole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="borePosition" type="{http://www.wwidesigner.com/Instrument}Dimension"/>
 *         &lt;element name="diameter" type="{http://www.wwidesigner.com/Instrument}MoreThanZero"/>
 *         &lt;element name="height" type="{http://www.wwidesigner.com/Instrument}MoreThanZero"/>
 *         &lt;element name="innerCurvatureRadius" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore" minOccurs="0"/>
 *         &lt;element name="key" type="{http://www.wwidesigner.com/Instrument}Key" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hole", propOrder = {
    "name",
    "borePosition",
    "diameter",
    "height",
    "innerCurvatureRadius",
    "key"
})
public class Hole {

    protected String name;
    protected double borePosition;
    protected double diameter;
    protected double height;
    protected Double innerCurvatureRadius;
    protected Key key;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public double getBorePosition() {
        return borePosition;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setBorePosition(double value) {
        this.borePosition = value;
    }

    /**
     * Gets the value of the diameter property.
     * 
     */
    public double getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     */
    public void setDiameter(double value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the innerCurvatureRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInnerCurvatureRadius() {
        return innerCurvatureRadius;
    }

    /**
     * Sets the value of the innerCurvatureRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInnerCurvatureRadius(Double value) {
        this.innerCurvatureRadius = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link Key }
     *     
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link Key }
     *     
     */
    public void setKey(Key value) {
        this.key = value;
    }

}
