//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 12:07:42 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Representation of a key mechanism over a tone
 * 				hole.
 * 			
 * 
 * <p>Java class for Key complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Key">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diameter" type="{http://www.wwidesigner.com/Instrument}MoreThanZero"/>
 *         &lt;element name="holeDiameter" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="height" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="thickness" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="wallThickness" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="chimneyHeight" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Key", propOrder = {
    "diameter",
    "holeDiameter",
    "height",
    "thickness",
    "wallThickness",
    "chimneyHeight"
})
public class Key {

    protected double diameter;
    protected double holeDiameter;
    protected double height;
    protected double thickness;
    protected double wallThickness;
    protected double chimneyHeight;

    /**
     * Gets the value of the diameter property.
     * 
     */
    public double getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     */
    public void setDiameter(double value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the holeDiameter property.
     * 
     */
    public double getHoleDiameter() {
        return holeDiameter;
    }

    /**
     * Sets the value of the holeDiameter property.
     * 
     */
    public void setHoleDiameter(double value) {
        this.holeDiameter = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the thickness property.
     * 
     */
    public double getThickness() {
        return thickness;
    }

    /**
     * Sets the value of the thickness property.
     * 
     */
    public void setThickness(double value) {
        this.thickness = value;
    }

    /**
     * Gets the value of the wallThickness property.
     * 
     */
    public double getWallThickness() {
        return wallThickness;
    }

    /**
     * Sets the value of the wallThickness property.
     * 
     */
    public void setWallThickness(double value) {
        this.wallThickness = value;
    }

    /**
     * Gets the value of the chimneyHeight property.
     * 
     */
    public double getChimneyHeight() {
        return chimneyHeight;
    }

    /**
     * Sets the value of the chimneyHeight property.
     * 
     */
    public void setChimneyHeight(double value) {
        this.chimneyHeight = value;
    }

}
