//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.30 at 09:14:21 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Representation of a key mechanism over a tone
 * 				hole.
 * 			
 * 
 * <p>Java class for Key complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Key">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diameter" type="{http://www.wwidesigner.com/Instrument}MoreThanZero"/>
 *         &lt;element name="holeDiameter" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="height" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="thickness" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="wallThickness" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *         &lt;element name="chimneyHeight" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Key", propOrder = {
    "diameter",
    "holeDiameter",
    "height",
    "thickness",
    "wallThickness",
    "chimneyHeight"
})
public class Key {

    @XmlElement(required = true)
    protected MoreThanZero diameter;
    @XmlElement(required = true)
    protected ZeroOrMore holeDiameter;
    @XmlElement(required = true)
    protected ZeroOrMore height;
    @XmlElement(required = true)
    protected ZeroOrMore thickness;
    @XmlElement(required = true)
    protected ZeroOrMore wallThickness;
    @XmlElement(required = true)
    protected ZeroOrMore chimneyHeight;

    /**
     * Gets the value of the diameter property.
     * 
     * @return
     *     possible object is
     *     {@link MoreThanZero }
     *     
     */
    public MoreThanZero getDiameter() {
        return diameter;
    }

    /**
     * Sets the value of the diameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoreThanZero }
     *     
     */
    public void setDiameter(MoreThanZero value) {
        this.diameter = value;
    }

    /**
     * Gets the value of the holeDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getHoleDiameter() {
        return holeDiameter;
    }

    /**
     * Sets the value of the holeDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setHoleDiameter(ZeroOrMore value) {
        this.holeDiameter = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setHeight(ZeroOrMore value) {
        this.height = value;
    }

    /**
     * Gets the value of the thickness property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getThickness() {
        return thickness;
    }

    /**
     * Sets the value of the thickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setThickness(ZeroOrMore value) {
        this.thickness = value;
    }

    /**
     * Gets the value of the wallThickness property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getWallThickness() {
        return wallThickness;
    }

    /**
     * Sets the value of the wallThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setWallThickness(ZeroOrMore value) {
        this.wallThickness = value;
    }

    /**
     * Gets the value of the chimneyHeight property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroOrMore }
     *     
     */
    public ZeroOrMore getChimneyHeight() {
        return chimneyHeight;
    }

    /**
     * Sets the value of the chimneyHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroOrMore }
     *     
     */
    public void setChimneyHeight(ZeroOrMore value) {
        this.chimneyHeight = value;
    }

}
