//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.30 at 09:14:21 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wwidesigner.com/Instrument")
package com.wwidesigner.geometry.bind;
