//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 12:07:42 PM MDT 
//


package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Description of the opening at the bottom end of
 * 				the instrument.
 * 			
 * 
 * <p>Java class for Termination complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Termination">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flangeDiameter" type="{http://www.wwidesigner.com/Instrument}ZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Termination", propOrder = {
    "flangeDiameter"
})
public class Termination {

    protected double flangeDiameter;

    /**
     * Gets the value of the flangeDiameter property.
     * 
     */
    public double getFlangeDiameter() {
        return flangeDiameter;
    }

    /**
     * Sets the value of the flangeDiameter property.
     * 
     */
    public void setFlangeDiameter(double value) {
        this.flangeDiameter = value;
    }

}
