//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Represents a bore position and effective diameter, measured from the head of
 * the instrument. Diameters between borePoints are linearly interpolated.
 * 
 * 
 * <p>
 * Java class for XmlBorePoint complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlBorePoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="borePosition" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="boreDiameter" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlBorePoint", propOrder = { "borePosition", "boreDiameter" })
@XmlSeeAlso({ XmlEndBoreSection.class })
public class XmlBorePoint
{

	@XmlElement(required = true)
	protected XmlZeroOrMore borePosition;
	@XmlElement(required = true)
	protected XmlZeroOrMore boreDiameter;

	/**
	 * Gets the value of the borePosition property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getBorePosition()
	{
		return borePosition;
	}

	/**
	 * Sets the value of the borePosition property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setBorePosition(XmlZeroOrMore value)
	{
		this.borePosition = value;
	}

	/**
	 * Gets the value of the boreDiameter property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getBoreDiameter()
	{
		return boreDiameter;
	}

	/**
	 * Sets the value of the boreDiameter property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setBoreDiameter(XmlZeroOrMore value)
	{
		this.boreDiameter = value;
	}

}
