//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Base class for a double value and associated optimization flag.
 * 
 * 
 * <p>
 * Java class for XmlDimension complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlDimension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="optimization" type="{http://www.wwidesigner.com/Instrument}XmlOptimization"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlDimension", propOrder = { "value", "optimization" })
@XmlSeeAlso({ XmlMoreThanZero.class, XmlZeroOrMore.class })
public class XmlDimension
{

	protected double value;
	@XmlElement(required = true)
	protected XmlOptimization optimization;

	/**
	 * Gets the value of the value property.
	 * 
	 */
	public double getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 */
	public void setValue(double value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the optimization property.
	 * 
	 * @return possible object is {@link XmlOptimization }
	 * 
	 */
	public XmlOptimization getOptimization()
	{
		return optimization;
	}

	/**
	 * Sets the value of the optimization property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlOptimization }
	 * 
	 */
	public void setOptimization(XmlOptimization value)
	{
		this.optimization = value;
	}

}
