//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The terminal borePoint of an instrument that also contains a flange value.
 * 
 * 
 * <p>
 * Java class for XmlEndBoreSection complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlEndBoreSection">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.wwidesigner.com/Instrument}XmlBorePoint">
 *       &lt;sequence>
 *         &lt;element name="flangeDiameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlEndBoreSection", propOrder = { "flangeDiameter" })
public class XmlEndBoreSection extends XmlBorePoint
{

	@XmlElement(required = true)
	protected XmlMoreThanZero flangeDiameter;

	/**
	 * Gets the value of the flangeDiameter property.
	 * 
	 * @return possible object is {@link XmlMoreThanZero }
	 * 
	 */
	public XmlMoreThanZero getFlangeDiameter()
	{
		return flangeDiameter;
	}

	/**
	 * Sets the value of the flangeDiameter property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMoreThanZero }
	 * 
	 */
	public void setFlangeDiameter(XmlMoreThanZero value)
	{
		this.flangeDiameter = value;
	}

}
