//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A tone hole with optional key mechanism. The tone hole assumes a cylindrical
 * shape with a radiused inner edge. More complexity is possible, including
 * truncated conical profiles and angled holes.
 * 
 * 
 * <p>
 * Java class for XmlHole complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlHole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="position" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="diameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *         &lt;element name="height" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *         &lt;element name="innerCurvatureRadius" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore" minOccurs="0"/>
 *         &lt;element name="key" type="{http://www.wwidesigner.com/Instrument}XmlKey" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlHole", propOrder = { "name", "position", "diameter",
		"height", "innerCurvatureRadius", "key" })
public class XmlHole
{

	protected String name;
	@XmlElement(required = true)
	protected XmlZeroOrMore position;
	@XmlElement(required = true)
	protected XmlMoreThanZero diameter;
	@XmlElement(required = true)
	protected XmlMoreThanZero height;
	protected XmlZeroOrMore innerCurvatureRadius;
	protected XmlKey key;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the position property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getPosition()
	{
		return position;
	}

	/**
	 * Sets the value of the position property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setPosition(XmlZeroOrMore value)
	{
		this.position = value;
	}

	/**
	 * Gets the value of the diameter property.
	 * 
	 * @return possible object is {@link XmlMoreThanZero }
	 * 
	 */
	public XmlMoreThanZero getDiameter()
	{
		return diameter;
	}

	/**
	 * Sets the value of the diameter property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMoreThanZero }
	 * 
	 */
	public void setDiameter(XmlMoreThanZero value)
	{
		this.diameter = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link XmlMoreThanZero }
	 * 
	 */
	public XmlMoreThanZero getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMoreThanZero }
	 * 
	 */
	public void setHeight(XmlMoreThanZero value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the innerCurvatureRadius property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getInnerCurvatureRadius()
	{
		return innerCurvatureRadius;
	}

	/**
	 * Sets the value of the innerCurvatureRadius property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setInnerCurvatureRadius(XmlZeroOrMore value)
	{
		this.innerCurvatureRadius = value;
	}

	/**
	 * Gets the value of the key property.
	 * 
	 * @return possible object is {@link XmlKey }
	 * 
	 */
	public XmlKey getKey()
	{
		return key;
	}

	/**
	 * Sets the value of the key property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlKey }
	 * 
	 */
	public void setKey(XmlKey value)
	{
		this.key = value;
	}

}
