//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Representation of a key mechanism over a tone hole.
 * 
 * 
 * <p>
 * Java class for XmlKey complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlKey">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *         &lt;element name="holeDiameter" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="height" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="thickness" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="wallThickness" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;element name="chimneyHeight" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlKey", propOrder = { "diameter", "holeDiameter", "height",
		"thickness", "wallThickness", "chimneyHeight" })
public class XmlKey
{

	@XmlElement(required = true)
	protected XmlMoreThanZero diameter;
	@XmlElement(required = true)
	protected XmlZeroOrMore holeDiameter;
	@XmlElement(required = true)
	protected XmlZeroOrMore height;
	@XmlElement(required = true)
	protected XmlZeroOrMore thickness;
	@XmlElement(required = true)
	protected XmlZeroOrMore wallThickness;
	@XmlElement(required = true)
	protected XmlZeroOrMore chimneyHeight;

	/**
	 * Gets the value of the diameter property.
	 * 
	 * @return possible object is {@link XmlMoreThanZero }
	 * 
	 */
	public XmlMoreThanZero getDiameter()
	{
		return diameter;
	}

	/**
	 * Sets the value of the diameter property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMoreThanZero }
	 * 
	 */
	public void setDiameter(XmlMoreThanZero value)
	{
		this.diameter = value;
	}

	/**
	 * Gets the value of the holeDiameter property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getHoleDiameter()
	{
		return holeDiameter;
	}

	/**
	 * Sets the value of the holeDiameter property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setHoleDiameter(XmlZeroOrMore value)
	{
		this.holeDiameter = value;
	}

	/**
	 * Gets the value of the height property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getHeight()
	{
		return height;
	}

	/**
	 * Sets the value of the height property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setHeight(XmlZeroOrMore value)
	{
		this.height = value;
	}

	/**
	 * Gets the value of the thickness property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getThickness()
	{
		return thickness;
	}

	/**
	 * Sets the value of the thickness property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setThickness(XmlZeroOrMore value)
	{
		this.thickness = value;
	}

	/**
	 * Gets the value of the wallThickness property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getWallThickness()
	{
		return wallThickness;
	}

	/**
	 * Sets the value of the wallThickness property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setWallThickness(XmlZeroOrMore value)
	{
		this.wallThickness = value;
	}

	/**
	 * Gets the value of the chimneyHeight property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getChimneyHeight()
	{
		return chimneyHeight;
	}

	/**
	 * Sets the value of the chimneyHeight property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setChimneyHeight(XmlZeroOrMore value)
	{
		this.chimneyHeight = value;
	}

}
