//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 10:20:05 AM MDT 
//

package com.wwidesigner.geometry.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * First pass at a sound-mechanism model. Represents a choice between (1) a
 * characteristic length, (2) a flute-type embouchure, and (3) a fipple
 * mechanism. We need to add reeds, end-blown flutes, etc.
 * 
 * 
 * <p>
 * Java class for XmlMouthpiece complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlMouthpiece">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://www.wwidesigner.com/Instrument}XmlZeroOrMore"/>
 *         &lt;choice>
 *           &lt;element name="characteristicLength" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *           &lt;element name="embouchureHole">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="innerDiameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                     &lt;element name="outerDiameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                     &lt;element name="length" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="fipple">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="width" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                     &lt;element name="length" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                     &lt;element name="fippleFactor" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlMouthpiece", propOrder = { "position",
		"characteristicLength", "embouchureHole", "fipple" })
public class XmlMouthpiece
{

	@XmlElement(required = true)
	protected XmlZeroOrMore position;
	protected XmlMoreThanZero characteristicLength;
	protected XmlMouthpiece.EmbouchureHole embouchureHole;
	protected XmlMouthpiece.Fipple fipple;

	/**
	 * Gets the value of the position property.
	 * 
	 * @return possible object is {@link XmlZeroOrMore }
	 * 
	 */
	public XmlZeroOrMore getPosition()
	{
		return position;
	}

	/**
	 * Sets the value of the position property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlZeroOrMore }
	 * 
	 */
	public void setPosition(XmlZeroOrMore value)
	{
		this.position = value;
	}

	/**
	 * Gets the value of the characteristicLength property.
	 * 
	 * @return possible object is {@link XmlMoreThanZero }
	 * 
	 */
	public XmlMoreThanZero getCharacteristicLength()
	{
		return characteristicLength;
	}

	/**
	 * Sets the value of the characteristicLength property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMoreThanZero }
	 * 
	 */
	public void setCharacteristicLength(XmlMoreThanZero value)
	{
		this.characteristicLength = value;
	}

	/**
	 * Gets the value of the embouchureHole property.
	 * 
	 * @return possible object is {@link XmlMouthpiece.EmbouchureHole }
	 * 
	 */
	public XmlMouthpiece.EmbouchureHole getEmbouchureHole()
	{
		return embouchureHole;
	}

	/**
	 * Sets the value of the embouchureHole property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMouthpiece.EmbouchureHole }
	 * 
	 */
	public void setEmbouchureHole(XmlMouthpiece.EmbouchureHole value)
	{
		this.embouchureHole = value;
	}

	/**
	 * Gets the value of the fipple property.
	 * 
	 * @return possible object is {@link XmlMouthpiece.Fipple }
	 * 
	 */
	public XmlMouthpiece.Fipple getFipple()
	{
		return fipple;
	}

	/**
	 * Sets the value of the fipple property.
	 * 
	 * @param value
	 *            allowed object is {@link XmlMouthpiece.Fipple }
	 * 
	 */
	public void setFipple(XmlMouthpiece.Fipple value)
	{
		this.fipple = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="innerDiameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *         &lt;element name="outerDiameter" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *         &lt;element name="length" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "innerDiameter", "outerDiameter",
			"length" })
	public static class EmbouchureHole
	{

		@XmlElement(required = true)
		protected XmlMoreThanZero innerDiameter;
		@XmlElement(required = true)
		protected XmlMoreThanZero outerDiameter;
		@XmlElement(required = true)
		protected XmlMoreThanZero length;

		/**
		 * Gets the value of the innerDiameter property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getInnerDiameter()
		{
			return innerDiameter;
		}

		/**
		 * Sets the value of the innerDiameter property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setInnerDiameter(XmlMoreThanZero value)
		{
			this.innerDiameter = value;
		}

		/**
		 * Gets the value of the outerDiameter property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getOuterDiameter()
		{
			return outerDiameter;
		}

		/**
		 * Sets the value of the outerDiameter property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setOuterDiameter(XmlMoreThanZero value)
		{
			this.outerDiameter = value;
		}

		/**
		 * Gets the value of the length property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getLength()
		{
			return length;
		}

		/**
		 * Sets the value of the length property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setLength(XmlMoreThanZero value)
		{
			this.length = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="width" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *         &lt;element name="length" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *         &lt;element name="fippleFactor" type="{http://www.wwidesigner.com/Instrument}XmlMoreThanZero"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "width", "length", "fippleFactor" })
	public static class Fipple
	{

		@XmlElement(required = true)
		protected XmlMoreThanZero width;
		@XmlElement(required = true)
		protected XmlMoreThanZero length;
		@XmlElement(required = true)
		protected XmlMoreThanZero fippleFactor;

		/**
		 * Gets the value of the width property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getWidth()
		{
			return width;
		}

		/**
		 * Sets the value of the width property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setWidth(XmlMoreThanZero value)
		{
			this.width = value;
		}

		/**
		 * Gets the value of the length property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getLength()
		{
			return length;
		}

		/**
		 * Sets the value of the length property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setLength(XmlMoreThanZero value)
		{
			this.length = value;
		}

		/**
		 * Gets the value of the fippleFactor property.
		 * 
		 * @return possible object is {@link XmlMoreThanZero }
		 * 
		 */
		public XmlMoreThanZero getFippleFactor()
		{
			return fippleFactor;
		}

		/**
		 * Sets the value of the fippleFactor property.
		 * 
		 * @param value
		 *            allowed object is {@link XmlMoreThanZero }
		 * 
		 */
		public void setFippleFactor(XmlMoreThanZero value)
		{
			this.fippleFactor = value;
		}

	}

}
