//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 12:07:42 PM MDT 
//


package com.wwidesigner.geometry;



/**
 * <p>Java class for LengthType.
 * 
 */
public enum LengthType {

    MM("mm"),
    IN("in");
    private final String value;

    LengthType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LengthType fromValue(String v) {
        for (LengthType c: LengthType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
