//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.28 at 02:04:37 PM MDT 
//


package com.wwidesigner.geometry;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edkort.flute.impedance.geometry package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Instrument_QNAME = new QName("http://www.wwidesigner.com/Geometry", "instrument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wwidesigner.impedance.geometry
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlInstrument }
     * 
     */
    public XmlInstrument createFlute() {
        return new XmlInstrument();
    }

    /**
     * Create an instance of {@link BorePoint }
     * 
     */
    public BorePoint createBorePoint() {
        return new BorePoint();
    }

    /**
     * Create an instance of {@link EndBoreSection }
     * 
     */
    public EndBoreSection createEndBoreSection() {
        return new EndBoreSection();
    }

    /**
     * Create an instance of {@link Embouchure }
     * 
     */
    public Embouchure createEmbouchure() {
        return new Embouchure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlInstrument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wwidesigner.com/Geometry", name = "instrument")
    public JAXBElement<XmlInstrument> createInstrument(XmlInstrument value) {
        return new JAXBElement<XmlInstrument>(_Instrument_QNAME, XmlInstrument.class, null, value);
    }

}
