//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 11:39:09 PM MDT 
//

package com.wwidesigner.optimization.bind;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConstraintType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ConstraintType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="DIMENSIONAL"/>
 *     &lt;enumeration value="DIMENSIONLESS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConstraintType")
@XmlEnum
public enum ConstraintType
{

	BOOLEAN, INTEGER, DIMENSIONAL, DIMENSIONLESS;

	public String value()
	{
		return name();
	}

	public static ConstraintType fromValue(String v)
	{
		return valueOf(v);
	}

}
