//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 11:39:09 PM MDT 
//

package com.wwidesigner.optimization.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The metadata for a single-value constraint
 * 
 * 
 * <p>
 * Java class for Constraint complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Constraint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.wwidesigner.com/Constraints}ConstraintType"/>
 *         &lt;element name="lowerBound" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="upperBound" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Constraint", propOrder = { "displayName", "category", "type",
		"lowerBound", "upperBound" })
public class Constraint
{

	@XmlElement(required = true)
	protected String displayName;
	@XmlElement(required = true)
	protected String category;
	@XmlElement(required = true)
	protected ConstraintType type;
	protected Double lowerBound;
	protected Double upperBound;

	/**
	 * Gets the value of the displayName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDisplayName()
	{
		return displayName;
	}

	/**
	 * Sets the value of the displayName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDisplayName(String value)
	{
		this.displayName = value;
	}

	/**
	 * Gets the value of the category property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategory()
	{
		return category;
	}

	/**
	 * Sets the value of the category property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategory(String value)
	{
		this.category = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link ConstraintType }
	 * 
	 */
	public ConstraintType getType()
	{
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link ConstraintType }
	 * 
	 */
	public void setType(ConstraintType value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the lowerBound property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getLowerBound()
	{
		return lowerBound;
	}

	/**
	 * Sets the value of the lowerBound property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setLowerBound(Double value)
	{
		this.lowerBound = value;
	}

	/**
	 * Gets the value of the upperBound property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getUpperBound()
	{
		return upperBound;
	}

	/**
	 * Sets the value of the upperBound property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setUpperBound(Double value)
	{
		this.upperBound = value;
	}

}
