//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.24 at 12:45:27 PM MDT 
//

package com.wwidesigner.optimization.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * A list of contiguous finger holes groups constrained to have the same
 * inter-hole spacing.
 * 
 * 
 * <p>
 * Java class for HoleGroups complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="HoleGroups">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="holeGroup" type="{http://www.wwidesigner.com/Constraints}HoleGroup" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HoleGroups", propOrder = { "holeGroup" })
public class HoleGroups
{

	protected List<HoleGroup> holeGroup;

	/**
	 * Gets the value of the holeGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the holeGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getHoleGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link HoleGroup }
	 * 
	 * 
	 */
	public List<HoleGroup> getHoleGroup()
	{
		if (holeGroup == null)
		{
			holeGroup = new ArrayList<HoleGroup>();
		}
		return this.holeGroup;
	}

	public void setHoleGroup(List<HoleGroup> aHoleGroup)
	{
		this.holeGroup = aHoleGroup;
	}

}
