//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 11:39:09 PM MDT 
//

package com.wwidesigner.optimization.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.wwidesigner.optimization.bind package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName _Constraints_QNAME = new QName(
			"http://www.wwidesigner.com/Constraints", "constraints");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.wwidesigner.optimization.bind
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link Constraints }
	 * 
	 */
	public Constraints createConstraints()
	{
		return new Constraints();
	}

	/**
	 * Create an instance of {@link Constraint }
	 * 
	 */
	public Constraint createConstraint()
	{
		return new Constraint();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Constraints }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.wwidesigner.com/Constraints",
			name = "constraints")
	public JAXBElement<Constraints> createConstraints(Constraints value)
	{
		return new JAXBElement<Constraints>(_Constraints_QNAME,
				Constraints.class, null, value);
	}

}
