//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 11:39:09 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.wwidesigner.com/Constraints")
package com.wwidesigner.optimization.bind;

