//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 08:05:26 PM MDT 
//

package com.wwidesigner.note.bind;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Fingering complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Fingering">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="note" type="{http://www.wwidesigner.com/Tuning}Note" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element name="openHole" type="{http://www.w3.org/2001/XMLSchema}boolean" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="openEnd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="optimizationWeight" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fingering", propOrder = { "note", "openHole", "openEnd", "optimizationWeight" })
public class Fingering
{

	protected Note note;
	@XmlElement(type = Boolean.class)
	protected List<Boolean> openHole;
	protected Boolean openEnd;
	protected Integer optimizationWeight;

	/**
	 * Gets the value of the note property.
	 * 
	 * @return possible object is {@link Note }
	 * 
	 */
	public Note getNote()
	{
		return note;
	}

	/**
	 * Sets the value of the note property.
	 * 
	 * @param value
	 *            allowed object is {@link Note }
	 * 
	 */
	public void setNote(Note value)
	{
		this.note = value;
	}

	/**
	 * Gets the value of the openHole property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the openHole property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOpenHole().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Boolean }
	 * 
	 * 
	 */
	public List<Boolean> getOpenHole()
	{
		if (openHole == null)
		{
			openHole = new ArrayList<Boolean>();
		}
		return this.openHole;
	}

	/**
	 * @param openHole
	 *            the openHole to set
	 */
	public void setOpenHole(List<Boolean> openHole)
	{
		this.openHole = openHole;
	}

	/**
	 * @return the openEnd state in the fingering
	 */
	public Boolean getOpenEnd()
	{
		return openEnd;
	}

	/**
	 * @param openEnd the openEnd state to set
	 */
	public void setOpenEnd(Boolean openEnd)
	{
		this.openEnd = openEnd;
	}

	public Integer getOptimizationWeight()
	{
		return optimizationWeight;
	}

	public void setOptimizationWeight(Integer optimizationWeight)
	{
		this.optimizationWeight = optimizationWeight;
	}

}
