//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.15 at 12:02:46 AM MDT 
//

package com.wwidesigner.note.bind;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for XmlFingeringPattern complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="XmlFingeringPattern">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numberOfHoles" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;sequence>
 *           &lt;element name="fingering" type="{http://www.wwidesigner.com/Tuning}XmlFingering" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlFingeringPattern", propOrder = { "name", "comment",
		"numberOfHoles", "fingering" })
@XmlSeeAlso({ XmlTuning.class })
public class XmlFingeringPattern
{

	@XmlElement(required = true)
	protected String name;
	protected String comment;
	@XmlElement(required = true)
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfHoles;
	protected List<XmlFingering> fingering;

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.wwidesigner.note.bind.TuningInterface#getName()
	 */
	public String getName()
	{
		return name;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.wwidesigner.note.bind.TuningInterface#setName(java.lang.String)
	 */
	public void setName(String value)
	{
		this.name = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.wwidesigner.note.bind.TuningInterface#getComment()
	 */
	public String getComment()
	{
		return comment;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.wwidesigner.note.bind.TuningInterface#setComment(java.lang.String)
	 */
	public void setComment(String value)
	{
		this.comment = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.wwidesigner.note.bind.TuningInterface#getNumberOfHoles()
	 */
	public BigInteger getNumberOfHoles()
	{
		return numberOfHoles;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.wwidesigner.note.bind.TuningInterface#setNumberOfHoles(java.math.
	 * BigInteger)
	 */
	public void setNumberOfHoles(BigInteger value)
	{
		this.numberOfHoles = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see com.wwidesigner.note.bind.TuningInterface#getFingering()
	 */
	public List<XmlFingering> getFingering()
	{
		if (fingering == null)
		{
			fingering = new ArrayList<XmlFingering>();
		}
		return this.fingering;
	}

}
