//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.25 at 08:12:14 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wwidesigner.com/Note")
package com.wwidesigner.note;
