//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2-70- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.25 at 08:12:14 PM MST 
//


package com.wwidesigner.impedance.note;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edkort.flute.impedance.note package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Temperament_QNAME = new QName("http://www.wwidesigner.com/Note", "temperament");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wwidesigner.impedance.note
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Temperament }
     * 
     */
    public Temperament createTemperament() {
        return new Temperament();
    }

    /**
     * Create an instance of {@link TemperamentNote }
     * 
     */
    public TemperamentNote createTemperamentNote() {
        return new TemperamentNote();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Temperament }{@code >}}
     * 
     */
    @XmlElementDecl(name = "temperament")
    public JAXBElement<Temperament> createTemperament(Temperament value) {
        return new JAXBElement<Temperament>(_Temperament_QNAME, Temperament.class, null, value);
    }

}
